# Generated by Django 4.2.5 on 2023-09-10 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('carrera', 'Carrera'), ('encuentro', 'Encuentro')], max_length=50)),
                ('image', models.ImageField(upload_to='eventos/')),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='comentario',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='galeriaevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
