# Generated by Django 4.2.5 on 2024-02-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
