# Generated by Django 4.2.5 on 2024-03-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='eventgalery',
            options={'verbose_name': 'Galeria', 'verbose_name_plural': 'Galerias'},
        ),
        migrations.AlterModelOptions(
            name='eventorganizer',
            options={'verbose_name': 'Organizador', 'verbose_name_plural': 'Organizadores'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Patrocinador', 'verbose_name_plural': 'Patrocinadores'},
        ),
    ]
