# Generated by Django 4.2.5 on 2024-02-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255, verbose_name='Nombres')),
                ('last_names', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('facebook', models.URLField(verbose_name='facebook')),
                ('instagram', models.URLField(verbose_name='instagram')),
                ('twitter', models.URLField(verbose_name='twitter')),
                ('web', models.URLField(verbose_name='web')),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activa')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activa')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
    ]
