# Generated by Django 4.2.5 on 2024-03-25 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_rename_post_news_alter_news_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='author',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_names',
        ),
        migrations.RemoveField(
            model_name='author',
            name='names',
        ),
        migrations.RemoveField(
            model_name='author',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='author',
            name='web',
        ),
        migrations.AddField(
            model_name='author',
            name='is_trainee',
            field=models.BooleanField(default=True, verbose_name='Esta en prueba'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
