# Generated by Django 4.2.5 on 2024-03-25 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 3, 25, 4, 43, 27, 173501, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
